name: feedbackusuario
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  shelf: ^1.4.1
  shelf_plus: ^1.9.0
  shelf_router: ^1.1.4
  shelf_multipart: ^1.0.0
  crypto: ^3.0.3
  get_it: ^7.6.7
  mysql1: ^0.20.0
  shelf_cors_headers: ^0.1.5
  shelf_static: ^1.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
